main_svc
Galyk-Ilya/java-explore-with-me pull request #4
Opened 2023-10-08 13:01 UTC by Galyk-Ilya

2023-10-09 11:46 UTC, kalitva requested changes

2023-10-09 11:46 UTC, kalitva commented on ewm-service/pom.xml
> +            <artifactId>hibernate-core</artifactId>
А зачем нам эти зависимости хибернэйта, они разве не подтягиваются вместе со spring-boot-starter-data-jpa?

2023-10-09 11:46 UTC, kalitva commented on ewm-service/pom.xml
> +            <artifactId>h2</artifactId>
Дублируешь объявление

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/category/controller/AdministrationCategoryController.java
> +        CategoryDto ans = categoryService.addCategory(categoryDto);
`ans` - странное название переменной

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/compilation/controller/CompilationController.java
> +                                          @RequestParam(name = "from", defaultValue = "0") @PositiveOrZero int from,
name указывать необязательно, спринг поймет имя из названия параметра метода

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/error/ApiError.java
> +    public <T> ApiError(HttpStatus status, String reason, String message, List<T> errors, String timestamp) {
Что за такой странный конструктор, который требует параметры, но игнорирует их

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/error/ErrorHandler.java
> +        log.error("error", exception);
`"error"` - сообщение об ошибке, которое ничего не говорит, абсолютно бесполезно. Логирование нужно нам разработчикам, чтобы понимать в чем дело. Замени на `exception.getMessage()`

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/event/repository/EventCustomRepository.java
> +    List<Event> findEventsForPublic(String text, List<Long> categories, Boolean paid,
Многовато параметров, создай дто для передачи всех значений одним объектом

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/event/service/EventService.java
> +    List<EventFullDto> findEventsForAdmin(List<Long> users, List<EventState> states, List<Long> categories,
То же самое, многовато параметров. Оптимально колчиство параметров метода - 1 или 2, 3 уже много, больше - плохо (исключение - методы спринговых контроллеров). Подумай как можно сократить количество параметров, например использовать Parameter Object паттерн https://www.baeldung.com/spring-enum-request-param#clone

2023-10-09 11:46 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        User user = userRepository.findById(id).orElseThrow(() -> new NotFoundException("Not found"));
Проверяй наличие юзера методом `existsById`

2023-10-09 11:46 UTC, kalitva commented on stats/stats-server/src/main/java/ru/practicum/stats/error/ErrorHandler.java
> +        log.info("Временные рамки заданы неверно");
Пожалуйста, по английски

2023-10-09 22:23 UTC, Galyk-Ilya commented
По параметрам понял, сейчас разберусь и поправлю, отправил на ревью, т.к. сроки поджимают, если кроме замечания по кол-ву параметров нет явных замечаний, прошу прожать, я постараюсь поправить в следующем пулреквесте)

2023-10-10 16:42 UTC, kalitva approved these changes

2023-10-10 16:42 UTC, kalitva commented on ewm-service/pom.xml
> +            <artifactId>hibernate-entitymanager</artifactId>
Разве не подтягивается вместе с spring-data-jpa

2023-10-10 16:42 UTC, kalitva commented on ewm-service/pom.xml
> +            <artifactId>validation-api</artifactId>
Подтягивается вместе с spring-boot-starter-validation

2023-10-10 16:42 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/category/controller/AdministrationCategoryController.java
> +@RequestMapping("/admin")
Может лучше `/admin/categories`

2023-10-10 16:42 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (!categories.isEmpty()) {
Нам точно нужна эта проверка? Что изменится если ее не будет

2023-10-10 16:42 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/error/ApiError.java
> +    public <T> ApiError(HttpStatus status, String reason, String message, List<T> errors, String timestamp) {
?

2023-10-10 18:58 UTC, Galyk-Ilya commented on ewm-service/src/main/java/ru/practicum/error/ApiError.java
> +    public <T> ApiError(HttpStatus status, String reason, String message, List<T> errors, String timestamp) {
Да, мой косяк, поправил логику, но забыл его удалить

2023-10-10 19:13 UTC, Galyk-Ilya commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (!categories.isEmpty()) {
Иначе падает постман тесты

2023-10-10 21:26 UTC, merged